### ISSUE TITLE
Add minimum maintenance tools

### ISSUE THREAD

**Issue by rgaudin** [offspot/base-image#21]
For development, debug and maintenance, it is occasionally required to log-into the Pi. To ease with the common tasks associated with such operations, the following packages, installed on the host, would help

- `vim-tiny` ~2.5M (`micro` is way larger)
- `screen` ~1M

FYI, `bash-completion`, `git`, `curl`, `wget`, `unzip`, `zip`, `p7zip-full` are already part of the distrib.

**Comment by rgaudin** [comment]
Agrees ; those are all useful for maintenance/debug. `tmux` is indeed a better choice than `screen`. I'd suggest `ncdu` as well.

We should maybe disable updatedb's cron entry as maintainer could run it when needed and it would satisfy #20

**Comment by fheslouin** [comment]
+1 for `ncdu` and disabling updatedb's cron entry

**Comment by letompouce** [comment]
Oops I'm late on this one!

These two packages sound like a must-have to me:
* `ncurses-term` because not everyone has `TERM=xterm` :-) (4,2Mb)
* `jq` to query/filter any JSON output/files (1,1Mb)

This one is just a shell convenience but is so lightweight:
* `tree` for filesystem exploration (118Kb)

**Comment by rgaudin** [comment]
@letompouce added them three 👍
