### ISSUE TITLE
Consider using podman

### ISSUE THREAD

**Issue by rgaudin** [offspot/base-image#7]
Podman might be a better alternative than docker-ce:

- daemon-less
- lighter than dockerd
- systemd integration (for use by OLIP in its post-install step)
- docker-compose and docker API compatible when using the podman service

**Comment by Bastien-BSF** [comment]
Thanks for recommending Podman. It seems to be an interesting alternative in the case of OLIP API.
I will need to check how we could make the switch.
Nonetheless I believe we will continue using Docker for the time being as our code base relies heavily on it and would need a considerable effort in order to improve this area. 
I will include considering the switch to Podman in my long term goals and let you know when we make some progress in this direction. In the meantime I will close the issue. Feel free to re-open it in case this is a feature you want to see included.
